# Generated by Django 5.2.8 on 2025-11-21 13:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')]}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'left'), ('center', 'center'), ('right', 'right')]}), 3: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1), ('text_align', 2)]], {})}),
        ),
    ]
