# Generated by Django 5.2.8 on 2025-11-21 14:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 3), ('paragraph', 5), ('image', 8), ('video', 10), ('spacer', 12), ('button_area', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')]}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'left'), ('center', 'center'), ('right', 'right')]}), 3: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1), ('text_align', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('content', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 6), ('caption', 7), ('attribution', 7)]], {}), 9: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('video', 9)]], {}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')]}), 12: ('wagtail.blocks.StructBlock', [[('height', 11)]], {}), 13: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.URLBlock', (), {'required': False}), 15: ('wagtail.blocks.StructBlock', [[('text', 0), ('page_link', 13), ('url_link', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('horizontal', 'Horizontal'), ('vertical', 'Vertical')]}), 18: ('wagtail.blocks.StructBlock', [[('buttons', 16), ('direction', 17), ('gap', 11)]], {})}),
        ),
    ]
