# Generated by Django 5.2.8 on 2025-11-21 14:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('container', 25)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('2', '2 Columns'), ('3', '3 Columns'), ('4', '4 Columns'), ('4/8', '4/8 Columns'), ('8/4', '8/4 Columns')]}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')]}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')]}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full'), ('auto', 'Auto')]}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')]}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'left'), ('center', 'center'), ('right', 'right')]}), 7: ('wagtail.blocks.StructBlock', [[('heading_text', 4), ('size', 5), ('text_align', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('content', 8)]], {}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('image', 10), ('caption', 11), ('attribution', 11)]], {}), 13: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 14: ('wagtail.blocks.StructBlock', [[('video', 13)]], {}), 15: ('wagtail.blocks.StructBlock', [[('height', 1)]], {}), 16: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.URLBlock', (), {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('text', 4), ('page_link', 16), ('url_link', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('horizontal', 'Horizontal'), ('vertical', 'Vertical')]}), 21: ('wagtail.blocks.StructBlock', [[('buttons', 19), ('direction', 20), ('gap', 1)]], {}), 22: ('wagtail.blocks.StreamBlock', [[('heading', 7), ('paragraph', 9), ('image', 12), ('video', 14), ('spacer', 15), ('button_area', 21)]], {'required': True}), 23: ('wagtail.blocks.StructBlock', [[('layout', 3), ('content', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {}), 25: ('wagtail.blocks.StructBlock', [[('layout', 0), ('gap', 1), ('padding_top', 2), ('padding_bottom', 2), ('columns', 24)]], {})}),
        ),
    ]
