# Generated by Django 5.2.8 on 2025-11-21 18:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('container', 26)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid-cols-1', 'Full'), ('md:grid-cols-[repeat(1,_34.625rem)] lg:grid-cols-[repeat(1,_28.5rem)] xl:grid-cols-[repeat(1,_36rem)] 3xl:grid-cols-[repeat(1,_47.25rem)]', 'Small'), ('lg:grid-cols-[repeat(1,_39rem)] xl:grid-cols-[repeat(1,_49rem)] 3xl:grid-cols-[repeat(1,_64rem)]', 'Medium'), ('lg:grid-cols-[repeat(1,_49.5rem)] xl:grid-cols-[repeat(1,_62rem)] 3xl:grid-cols-[repeat(1,_80.75rem)]', 'Large'), ('grid-cols-2', '2 Columns'), ('grid-cols-3', '3 Columns'), ('grid-cols-4', '4 Columns'), ('lg:grid-cols-[1fr_2fr]', '4/8 Columns'), ('lg:grid-cols-[2fr_1fr]', '8/4 Columns')]}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L')]}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')]}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full'), ('auto', 'Auto')]}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')]}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'left'), ('center', 'center'), ('right', 'right')]}), 7: ('wagtail.blocks.StructBlock', [[('heading_text', 4), ('size', 5), ('text_align', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('content', 8)]], {}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('image', 10), ('caption', 11), ('attribution', 11)]], {}), 13: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 14: ('wagtail.blocks.StructBlock', [[('video', 13)]], {}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('4', '4'), ('8', '8'), ('12', '12'), ('24', '24'), ('32', '32')]}), 16: ('wagtail.blocks.StructBlock', [[('height', 15)]], {}), 17: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 18: ('wagtail.blocks.URLBlock', (), {'required': False}), 19: ('wagtail.blocks.StructBlock', [[('text', 4), ('page_link', 17), ('url_link', 18)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('horizontal', 'Horizontal'), ('vertical', 'Vertical')]}), 22: ('wagtail.blocks.StructBlock', [[('buttons', 20), ('direction', 21), ('gap', 1)]], {}), 23: ('wagtail.blocks.StreamBlock', [[('heading', 7), ('paragraph', 9), ('image', 12), ('video', 14), ('spacer', 16), ('button_area', 22)]], {'required': True}), 24: ('wagtail.blocks.StructBlock', [[('layout', 3), ('content', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {}), 26: ('wagtail.blocks.StructBlock', [[('layout', 0), ('gap_x', 1), ('gap_y', 1), ('padding_top', 2), ('padding_bottom', 2), ('columns', 25)]], {})}),
        ),
    ]
