# Generated by Django 5.2.8 on 2025-11-29 22:49

import django.core.validators
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('icon', models.CharField(choices=[('home', 'Home'), ('folder', 'Folder'), ('briefcase', 'Briefcase'), ('tool', 'Tool'), ('contact', 'Contact')], default='home', max_length=15)),
                ('link', wagtail.fields.StreamField([('link', 5)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Internal'), ('external', 'External'), ('mailto', 'Mailto')]}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False, 'validators': [django.core.validators.EmailValidator()]}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('link_type', 0), ('page_link', 1), ('url', 2), ('mailto', 3), ('link_text', 4)]], {})}, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Advert',
        ),
    ]
