# Generated by Django 5.2.8 on 2025-11-29 23:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_menu_delete_advert'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='link',
        ),
        migrations.AddField(
            model_name='menu',
            name='link_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='link_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('mailto', 'Mailto')], default='internal', max_length=10),
        ),
        migrations.AddField(
            model_name='menu',
            name='mailto',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='menu',
            name='page_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
