# Generated by Django 5.2.8 on 2025-11-29 23:14

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_menu_link_menu_link_text_menu_link_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='link_text',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='link_type',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='mailto',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='page_link',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
        migrations.AddField(
            model_name='menu',
            name='link',
            field=wagtail.fields.StreamField([('link', 5)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Internal'), ('external', 'External'), ('mailto', 'Mailto')]}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False, 'validators': [django.core.validators.EmailValidator()]}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('link_type', 0), ('page_link', 1), ('url', 2), ('mailto', 3), ('link_text', 4)]], {})}, null=True),
        ),
    ]
