# Generated by Django 5.2.8 on 2025-11-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_menu_locked_menu_locked_at_menu_locked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='label',
            new_name='name',
        ),
    ]
