# Generated by Django 5.2.8 on 2025-11-30 21:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_menu_page_link_article'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='link_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='link_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('mailto', 'Mailto')], default='internal', max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='mailto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='page_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraphs',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='reading_time',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
