# Generated by Django 5.2.8 on 2025-12-01 00:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_article_date_article_link_text_article_link_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, null=True, validators=[wagtail.fields.NoFutureDateValidator()]),
        ),
    ]
