# Generated by Django 5.2.8 on 2025-12-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_article_anchor_article_document_article_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='anchor',
        ),
        migrations.RemoveField(
            model_name='article',
            name='document',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='mailto',
        ),
        migrations.RemoveField(
            model_name='article',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='document',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='mailto',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='phone',
        ),
        migrations.AlterField(
            model_name='article',
            name='link_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='link_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('anchor', 'Anchor')], default='internal', max_length=10),
        ),
    ]
