# Generated by Django 5.2.8 on 2025-12-06 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_article_anchor_remove_article_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='paragraphs',
            new_name='paragraph',
        ),
    ]
