# Generated by Django 5.2.8 on 2025-12-07 02:29

import django.core.validators
import django.db.models.deletion
import modelsearch.index
import wagtail.fields
import wagtail.models.preview
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_paragraphs_article_paragraph'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='imagen',
            new_name='image',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('locked', models.BooleanField(default=False, editable=False, verbose_name='locked')),
                ('locked_at', models.DateTimeField(editable=False, null=True, verbose_name='locked at')),
                ('name', models.CharField(max_length=255)),
                ('about_me', wagtail.fields.RichTextField(blank=True)),
                ('social_links', wagtail.fields.StreamField([('icon', 0), ('link', 9)], block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('email', 'Email'), ('linkedin', 'LinkedIn'), ('github', 'GitHub')]}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Internal'), ('external', 'External'), ('mailto', 'Mailto'), ('phone', 'Phone'), ('image', 'Image'), ('document', 'Document'), ('anchor', 'Anchor')]}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'required': False, 'validators': [django.core.validators.EmailValidator()]}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'required': True}), 9: ('wagtail.blocks.StructBlock', [[('link_type', 1), ('page_link', 2), ('url', 3), ('mailto', 4), ('phone', 5), ('image', 6), ('document', 7), ('anchor', 5), ('link_text', 8)]], {'required': True})})),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('locked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
            bases=(modelsearch.index.Indexed, wagtail.models.preview.PreviewableMixin, models.Model),
        ),
    ]
