# Generated by Django 5.2.8 on 2025-12-07 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_imagen_article_image_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
