# Generated by Django 5.2.8 on 2025-12-07 02:37

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_links',
            field=wagtail.fields.StreamField([('networks', 11)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('email', 'Email'), ('linkedin', 'LinkedIn'), ('github', 'GitHub')]}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Internal'), ('external', 'External'), ('mailto', 'Mailto'), ('phone', 'Phone'), ('image', 'Image'), ('document', 'Document'), ('anchor', 'Anchor')]}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'required': False, 'validators': [django.core.validators.EmailValidator()]}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'required': True}), 9: ('wagtail.blocks.StructBlock', [[('link_type', 1), ('page_link', 2), ('url', 3), ('mailto', 4), ('phone', 5), ('image', 6), ('document', 7), ('anchor', 5), ('link_text', 8)]], {'required': True}), 10: ('wagtail.blocks.StructBlock', [[('icon', 0), ('link', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {})}, null=True),
        ),
    ]
