# Generated by Django 5.2.8 on 2025-12-07 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_profile_social_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='hero',
        ),
    ]
