# Generated by Django 5.2.8 on 2025-11-25 02:03

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('container', 55)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid-cols-1', 'Full'), ('md:grid-cols-[repeat(1,_34.625rem)] lg:grid-cols-[repeat(1,_28.5rem)] xl:grid-cols-[repeat(1,_36rem)] 3xl:grid-cols-[repeat(1,_47.25rem)]', 'Small'), ('lg:grid-cols-[repeat(1,_39rem)] xl:grid-cols-[repeat(1,_49rem)] 3xl:grid-cols-[repeat(1,_64rem)]', 'Medium'), ('lg:grid-cols-[repeat(1,_49.5rem)] xl:grid-cols-[repeat(1,_62rem)] 3xl:grid-cols-[repeat(1,_80.75rem)]', 'Large'), ('lg:grid-cols-2', '2 Columns'), ('md:grid-cols-3', '3 Columns'), ('md:grid-cols-4', '4 Columns'), ('lg:grid-cols-[1fr_2fr]', '4/8 Columns'), ('lg:grid-cols-[2fr_1fr]', '8/4 Columns')]}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gap-x-0', 'None'), ('gap-x-3', 'XXS'), ('gap-x-4', 'XS'), ('gap-x-5 lg:gap-x-6', 'S'), ('gap-x-7 lg:gap-x-9', 'M'), ('gap-x-9 lg:gap-x-12', 'L')]}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gap-y-0', 'None'), ('gap-y-3', 'XXS'), ('gap-y-4', 'XS'), ('gap-y-5 lg:gap-y-6', 'S'), ('gap-y-7 lg:gap-y-9', 'M'), ('gap-y-9 lg:gap-y-12', 'L')]}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('pt-0', 'None'), ('pt-6', 'XXS'), ('pt-8 lg:pt-9', 'XS'), ('pt-10 lg:pt-12', 'S'), ('pt-12 lg:pt-16', 'M'), ('pt-16 lg:pt-24', 'L'), ('pt-24 lg:pt-36', 'XL'), ('pt-40 lg:pt-50', 'XXL')]}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('pb-0', 'None'), ('pb-6', 'XXS'), ('pb-8 lg:pb-9', 'XS'), ('pb-10 lg:pb-12', 'S'), ('pb-12 lg:pb-16', 'M'), ('pb-16 lg:pb-24', 'L'), ('pb-24 lg:pb-36', 'XL'), ('pb-40 lg:pb-50', 'XXL')]}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('col-span-full', 'Full'), ('col-auto', 'Auto')]}), 6: ('wagtail.blocks.CharBlock', (), {'required': True}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')]}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text-left', 'left'), ('text-center', 'center'), ('text-right', 'right')]}), 9: ('wagtail.blocks.StructBlock', [[('heading_text', 6), ('size', 7), ('text_align', 8)]], {}), 10: ('wagtail.blocks.RichTextBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('content', 10)]], {}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('image', 12), ('caption', 13), ('attribution', 13)]], {}), 15: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 16: ('wagtail.blocks.StructBlock', [[('video', 15)]], {}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h-6', 'XXS'), ('h-8 lg:h-9', 'XS'), ('h-10 lg:h-12', 'S'), ('h-12 lg:h-16', 'M'), ('h-16 lg:h-24', 'L'), ('h-24 lg:h-36', 'XL'), ('h-40 lg:h-50', 'XXL'), ('h-1', '4'), ('h-2', '8'), ('h-3', '12'), ('h-4', '16'), ('h-5', '20'), ('h-6', '24'), ('h-8', '32')]}), 18: ('wagtail.blocks.StructBlock', [[('height', 17)]], {}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Internal'), ('external', 'External'), ('mailto', 'Mailto')]}), 20: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 21: ('wagtail.blocks.URLBlock', (), {'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'required': False, 'validators': [django.core.validators.EmailValidator()]}), 23: ('wagtail.blocks.StructBlock', [[('link_type', 19), ('page_link', 20), ('url', 21), ('mailto', 22), ('link_text', 6)]], {'required': False}), 24: ('wagtail.blocks.StructBlock', [[('link', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('horizontal', 'Horizontal'), ('vertical', 'Vertical')]}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gap-0', 'None'), ('gap-3', 'XXS'), ('gap-4', 'XS'), ('gap-5 lg:gap-6', 'S'), ('gap-7 lg:gap-9', 'M'), ('gap-9 lg:gap-12', 'L')]}), 28: ('wagtail.blocks.StructBlock', [[('buttons', 25), ('direction', 26), ('gap', 27)]], {}), 29: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('email', 'Email'), ('linkedin', 'LinkedIn'), ('github', 'GitHub')]}), 30: ('wagtail.blocks.StructBlock', [[('link_type', 19), ('page_link', 20), ('url', 21), ('mailto', 22), ('link_text', 6)]], {'required': True}), 31: ('wagtail.blocks.StructBlock', [[('icon', 29), ('link', 30)]], {}), 32: ('wagtail.blocks.ListBlock', (31,), {}), 33: ('wagtail.blocks.StructBlock', [[('image', 12), ('name', 6), ('about_me', 6), ('social_links', 32)]], {}), 34: ('wagtail.blocks.StructBlock', [[('line_one', 6), ('line_two', 6), ('size', 7), ('text_align', 8)]], {}), 35: ('wagtail.blocks.StructBlock', [[('number', 6), ('title', 6)]], {}), 36: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('flex-col', 'Vertical'), ('flex-row', 'Horizontal')]}), 37: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('items-start', 'Start'), ('items-center', 'Center'), ('items-end', 'End')]}), 38: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('justify-start', 'Start'), ('justify-center', 'Center'), ('justify-end', 'End'), ('justify-between', 'Between'), ('justify-around', 'Around'), ('justify-evenly', 'Evenly')]}), 39: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bg-portfolio-orange', 'Orange'), ('bg-portfolio-green', 'Green')]}), 40: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('dynamic', 'Dynamic'), ('square', 'Square')]}), 41: ('wagtail.blocks.StructBlock', [[('title', 6), ('link', 30), ('background', 39), ('icon', 40)]], {}), 42: ('wagtail.blocks.StructBlock', [[('image', 12), ('heading', 6), ('subheading', 6), ('link', 30)]], {}), 43: ('wagtail.blocks.StreamBlock', [[('informative_number', 35), ('card_skill', 41), ('tool_card', 42)]], {}), 44: ('wagtail.blocks.StructBlock', [[('direction', 36), ('vertical_alignment', 37), ('horizontal_alignment', 38), ('gap', 27), ('content', 43)]], {}), 45: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid-cols-1', 'Full'), ('lg:grid-cols-2', '2 Columns'), ('md:grid-cols-3', '3 Columns'), ('md:grid-cols-4', '4 Columns'), ('lg:grid-cols-[1fr_2fr]', '4/8 Columns'), ('lg:grid-cols-[2fr_1fr]', '8/4 Columns')]}), 46: ('wagtail.blocks.StructBlock', [[('layout', 45), ('gap', 27), ('content', 43)]], {}), 47: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 48: ('wagtail.blocks.DateBlock', (), {'required': True, 'validators': [wagtail.fields.NoFutureDateValidator()]}), 49: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 50: ('wagtail.blocks.StructBlock', [[('heading', 6), ('paragraph', 47), ('link', 30), ('from_date', 48), ('to_date', 48), ('current', 49)]], {}), 51: ('wagtail.blocks.StructBlock', [[('heading', 6), ('paragraph', 47), ('link', 30), ('date', 48), ('reading_time', 6)]], {}), 52: ('wagtail.blocks.StreamBlock', [[('heading', 9), ('paragraph', 11), ('image', 14), ('video', 16), ('spacer', 18), ('button_area', 28), ('profile_card', 33), ('heading_with_two_lines', 34), ('informative_number', 35), ('box', 44), ('box_grid', 46), ('project_card', 42), ('experience_card', 50), ('tool_card', 42), ('article_card', 51)]], {'required': True}), 53: ('wagtail.blocks.StructBlock', [[('layout', 5), ('content', 52)]], {}), 54: ('wagtail.blocks.ListBlock', (53,), {}), 55: ('wagtail.blocks.StructBlock', [[('layout', 0), ('gap_x', 1), ('gap_y', 2), ('padding_top', 3), ('padding_bottom', 4), ('columns', 54)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('thank_you_heading', models.CharField(blank=True)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='basic.formpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
