# Generated by Django 5.2.8 on 2025-11-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_alter_basicpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='field_width',
            field=models.CharField(choices=[('auto', 'Auto'), ('full', 'Full')], default='auto', max_length=10),
        ),
    ]
