# Generated by Django 5.2.8 on 2025-11-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_formfield_field_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_width',
            field=models.CharField(choices=[('col-span-1', 'Auto'), ('col-span-full', 'Full')], default='col-span-1', max_length=15),
        ),
    ]
